---
title: "[C++] Chapter.14 예외처리"
date: 2022-09-24 22:20:19 +0900
categories: [Language ,C++]
tags: [c++]
---
<hr>


## 예외처리의 기본
```cpp
// 예외 처리의 기본
// Exception Handing
#include <iostream>
#include <string>
#include <fstream>
#include <algorithm>
#include <cmath>

using namespace std;

//ch가 존재하는 문자열인지 확인 하는 함수
int findFirstChar(const char * string, char ch)
{
    for (std::size_t idx = 0; idx < strlen(string); ++idx) {
        if(string[idx] == ch)
            return idx;
    }
    
    //ch가 존재하지않는다면 -1 반환
    //예외처리 부분
    return -1;
}

double divide(int x, int y, bool &success)
{
    //0으로 나눌수없으므로 0.0을 반환
    if(y == 0)
    {
        success = false;
        return 0.0;
    }
    
    success = true;
    return static_cast<double>(x) / y;
}

int main() {
    //이번에는 예외처리에 대해 알아보자
    
    //좋은 프로그래머가 되기 위해 비정상적인 상황에 대해 안정적으로 실행이 되도록 만들어야 한다.
    //비정상적인 상황, 즉 예외적인 상황에 처리를 하는것을 예외처리라고 한다.
    //이번에는 기본적인 방법에 대해 알아보자
    
    
    bool success;
    double result = divide(5, 3, success);
    
    if(!success)
        std::cerr << "An Error occurred" << std::endl;      //오류 발생시 오류문구 출력
    else
        std::cout << "Result is " << result << std::endl;   //정상 작동시 결과 값 출력
    
    std::ifstream input_file("temp.txt");
    //파일 존재 유무 확인
    if(!input_file)
        std::cerr << "Cannot open file" << endl;    //파일이 없는경우 오류 문구 출력
    
    //이 예외처리 방식은 깔끔하지 않아보이지만 전통적인 C++방식으로는 이런식으로 많이 작성했다.
    //1. 퍼포먼스 측면에서 좋다.
    //2. 대체방법이 없었다.
    
    //다음에 배울 예외처리는 관점이 약간 달라진다.
    //다음에 배울 throw, try-catch방식은 깔끔해보이지만
    //퍼포먼스가 낮아진다.
    //퍼포먼스 중요한 경우 잘 사용하지 않는다.
    
    
    //예외처리를 사용하는경우
    //예측할수없는경우
    //서버의 경우 - 네트워크의 경우 - 갑자기 다운 되는 경우
    
    //예외처리를 안사용하는 분야도 존재하지만, 사용을 해야한다면 반드시 모든 오류 상황에 대해 예외처리를 해주어야한다.
    
    
    //기초적인 문법
    //try, catch, throw
    
    //throw - 오류를 던진다!
    
    //catch - 오류를 받는다!
    
    double x;
    cin >> x;
    
    try
    {
        if(x < 0.0) throw std::string("Negative input");
        //음수의 경우 오류 메시지를 날려준다.
        
        cout << sqrt(x) << endl;
    }
    //throw된 정보를 받는다.
    catch(std::string error_message)
    {
        //error_message에 throw로 날려준 string값을 catch하여 가져온다.
        cout << error_message << endl;
    }
    
    
    //주의사항
    //auto casting이 안된다.
    //throw와 오류를 받는 catch에 자료형이 같게 만들어줘야한다.
    
    
    try {
        throw -1.0;
        //throw -1.0; 인경우 double형이므로 catch에서 오류 발생
    }
    catch (int x) {
        cout << "Catch integer" << x  << endl;
    }
    catch (double x) {
        cout << "Catch double" << x  << endl;
    }
    catch(std::string error_message)
    {
        //error_message에 throw로 날려준 string값을 catch하여 가져온다.
        cout << error_message << endl;
    }
    //catch문이 여러개를 사용할수있다.
    //해당 오류에 관한 자료형의 catch가 없는경우 오류를 받아줄수있는곳이 없으므로 오류가 컴파일 오류가 발생한다.
    //throw와 catch의 자료형 타입이 같아야한다.
    
    return 0;
}
```

## 예외처리와 스택 되감기
```cpp
```
## 예외 클래스와 상속
```cpp
```
## exception 소개
```cpp
```
## 함수 try
```cpp
```
## 예외처리의 위험성과 단점
```cpp
```